name: Run gulp tasks

# Controls when the action will run.
on:
  push:
    # On which branch
    branches: ["gulp4"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    # Runner name
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: gulp dist

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git status
          git add -A
          git commit -m "update gulp output files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_GITHUB_TOKEN }}
          # force: true